consumes:
- application/json
info:
  description: For use with the Garden Sentry application
  title: Garden Sentry API
  version: 1.0.0
paths:
  /v1/events/:
    get:
      operationId: getEvents
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: List the GS events
          schema:
            type: array
            items:
              $ref: "#/definitions/event"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      operationId: addEvent
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/event"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/event"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /v1/events/{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      operationId: getEventById
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/event'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    put:
      operationId: updateEvent
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/event"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/event"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      operationId: deleteEvent
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
paths:
  /v1/events/{id}/vids:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    post:
      consumes:
        - multipart/form-data
      parameters:
        - type: file
          in: formData
          name: upfile
          description: The file to upload.
          required: true
      operationId: uploadVideoToEvent
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/event'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  event:
    type: object
    required:
      - description
      - type
      - timestamp
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      type:
        type: string
        minLength: 1
      timestamp:
        type: string
      vidUrl:
        type: string
        minLength: 1
